services:
  - type: web
    name: cyber-prompt-builder
    env: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: REACT_APP_APP_ENVIRONMENT
        value: production
      - key: REACT_APP_PUBLIC_URL
        value: /
      - key: REACT_APP_PROVIDERS_OPENAI_API_KEY
        sync: false
      - key: REACT_APP_PROVIDERS_CLAUDE_API_KEY
        sync: false
      - key: REACT_APP_PROVIDERS_GEMINI_API_KEY
        sync: false
    # Auto-deploy from main branch
    autoDeploy: true
    # Build settings
    buildFilter:
      paths:
        - src/**
        - public/**
        - frontend/**
        - backend/**
        - shared/**
        - package.json
        - package-lock.json
        - vite.config.ts
        - tsconfig*.json
        - index.html
        - server.js
        - check-build.js
        - .env.production
    # Headers for security
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff