services:
  - type: web
    name: cyber-prompt-builder
    env: node
    plan: free
    buildCommand: npm ci && npm run build && npm run build:check
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Auto-deploy from main branch
    autoDeploy: true
    # Build settings
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - package-lock.json
        - vite.config.ts
        - tsconfig*.json
        - index.html
        - server.js
        - check-build.js
    # Headers for security
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff